In [24]:
import itertools
import random
import datetime
import os
import json

import pandas as pd
import numpy as np
import tensorflow as tf
import sentencepiece as spm

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix, f1_score

from tokenization_and_embedding import TokenAndPositionEmbedding
from transformer_block import TransformerBlock

# Dataset https://www.kaggle.com/code/aadyasingh55/model-training-of-tweet-emotion-classification


In [25]:
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(gpu, True)
print("GPUs:", gpus)

GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [26]:
df = pd.read_parquet('data.parquet')

print(df.head())
print(df['label'])

# Map the labels to emotion names for better readability (Optional)
emotion_map = {0: 'sadness', 1: 'joy', 2: 'love', 3: 'anger', 4: 'fear', 5: 'surprise'}
df['emotion'] = df['label'].map(emotion_map)

# Preview the updated dataframe
print(df[['text', 'emotion']].head())

                                                text  label
0  i feel awful about it too because it s my job ...      0
1                              im alone i feel awful      0
2  ive probably mentioned this before but i reall...      1
3           i was feeling a little low few days back      0
4  i beleive that i am much more sensitive to oth...      2
0         0
1         0
2         1
3         0
4         2
         ..
416804    1
416805    4
416806    0
416807    1
416808    0
Name: label, Length: 416809, dtype: int64
                                                text  emotion
0  i feel awful about it too because it s my job ...  sadness
1                              im alone i feel awful  sadness
2  ive probably mentioned this before but i reall...      joy
3           i was feeling a little low few days back  sadness
4  i beleive that i am much more sensitive to oth...     love


In [27]:
### Constants

# Training Vars
EPOCHS = 7
PATIENCE = 1
BATCH_SIZE = 128
LEARNING_RATE = 3e-4

# Model vars
EMBED_DIM = 128
NUM_HEADS = 4
FF_DIM = 256
DENSE_UNITS = 128
DROPOUT = 0.1
SHUFFLE_BUFFER = 10000

SEEDS = [42, 7]

# Params Grid
# sweep = {
#     "num_layers": [1, 2],
#     "num_heads": [4],
#     "ff_dim": [256],
#     "dropout": [0.1, 0.2],
#     "lr": [3e-4, 1e-4],
#     "dense_units": [128, 256],
# }

# sweep = {
#     "num_layers": [2],
#     "num_heads": [4],
#     "ff_dim": [128, 256],
#     "dropout": [0.1, 0.2],
#     "lr": [3e-4],
#     "dense_units": [128, 256],
# }

sweep = {
    "num_layers": [2, 3, 4],
    "num_heads": [4, 5, 6],
    "ff_dim": [128, 256],
    "dropout": [0.1],
    "lr": [3e-4],
    "dense_units": [128]
}

# Tokeniser / padding
PAD_ID = 3
BPE_PREFIX = "m_bpe"
UNIGRAM_PREFIX = "m_uni"

# RNN Vars
RNN_UNITS = 128
RNN_DROPOUT = 0.2
LABEL_SMOOTHING = 0.05
WEIGHT_DECAY = 1e-4

VOCAB_SIZE = 8000
# NUMBER_OF_LAYERS = 2 # not use while testing params table
TRAIN_TEXT = 'train_text.txt'
LABEL_FILE = 'train_labels.txt'
SAMPLE_TEXT = "This is a sample sentence used for BPE bits. It can be up to 128 characters long."
TOKEN_LENGTH = 128

In [28]:
def set_all_seeds(seed: int):
    np.random.seed(seed)
    tf.random.set_seed(seed)
    random.seed(seed)


In [29]:
#BASIC PRE PROCESSING
print(df.shape)
print(df.columns)
print(f"Data Types: {df.dtypes}")
print(f"Empty values {df.isna().sum()}")
print(f"Duplicates: {df.duplicated().sum()}")
print(df["label"].value_counts())
print(df["label"].value_counts(normalize=True).round(3))

(416809, 3)
Index(['text', 'label', 'emotion'], dtype='object')
Data Types: text       object
label       int64
emotion    object
dtype: object
Empty values text       0
label      0
emotion    0
dtype: int64
Duplicates: 686
label
1    141067
0    121187
3     57317
4     47712
2     34554
5     14972
Name: count, dtype: int64
label
1    0.338
0    0.291
3    0.138
4    0.114
2    0.083
5    0.036
Name: proportion, dtype: float64


In [30]:
from sklearn.model_selection import train_test_split

X = df["text"].astype(str)
y = df["label"].astype(int)

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

# Second split to obtain validation as well as test set
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

print(f"Feature Distribution (After Stratification)")
print(f"Train(%): {y_train.value_counts(normalize=True).round(5).sort_index() * 100}\n")
print(f"Val(%): {y_val.value_counts(normalize=True).round(5).sort_index() * 100}\n")
print(f"Test(%): {y_test.value_counts(normalize=True).round(5).sort_index() * 100}\n")

Feature Distribution (After Stratification)
Train(%): label
0    29.075
1    33.844
2     8.290
3    13.752
4    11.447
5     3.592
Name: proportion, dtype: float64

Val(%): label
0    29.076
1    33.845
2     8.289
3    13.752
4    11.446
5     3.592
Name: proportion, dtype: float64

Test(%): label
0    29.076
1    33.845
2     8.292
3    13.750
4    11.446
5     3.592
Name: proportion, dtype: float64



In [31]:
text_lengths = X_train.str.split().apply(len)
print(text_lengths.describe())

count    333447.000000
mean         19.200329
std          11.046795
min           1.000000
25%          11.000000
50%          17.000000
75%          25.000000
max         178.000000
Name: text, dtype: float64


In [32]:
X_train_clean = X_train.str.strip()
X_val_clean = X_val.str.strip()
X_test_clean = X_test.str.strip()

X_train_clean.to_csv(TRAIN_TEXT, index=False, header=False)
print(f"Wrote {len(X_train_clean)} to file")

Wrote 333447 to file


In [33]:
### Byte Pair Encoding (BPE)

if not os.path.exists(f"{BPE_PREFIX}.model"):
    spm.SentencePieceTrainer.train(
        input=TRAIN_TEXT,
        model_prefix= BPE_PREFIX,
        vocab_size=VOCAB_SIZE,
        model_type='bpe',
        pad_id=PAD_ID,
        unk_id=0,
        bos_id=1,
        eos_id=2
    )
    
sp_bpe = spm.SentencePieceProcessor()
sp_bpe.load(f'{BPE_PREFIX}.model')

### UNIGRAM
if not os.path.exists(f"{UNIGRAM_PREFIX}.model"):

    spm.SentencePieceTrainer.train(
        input=TRAIN_TEXT,
        model_prefix=UNIGRAM_PREFIX,
        vocab_size=VOCAB_SIZE,
        model_type='unigram',
        pad_id=PAD_ID,
        unk_id=0,
        bos_id=1,
        eos_id=2
    )
    
sp_uni = spm.SentencePieceProcessor()
sp_uni.load(f"{UNIGRAM_PREFIX}.model")

print(f"Vocab size: {sp_bpe.get_piece_size()}")
print(f"BPE Pieces: {sp_bpe.encode(SAMPLE_TEXT, out_type=str)[:50]}")
print(f"Uni Pieces: {sp_uni.encode(SAMPLE_TEXT, out_type=str)[:50]}")

Vocab size: 8000
BPE Pieces: ['▁', 'T', 'h', 'is', '▁is', '▁a', '▁sam', 'ple', '▁sentence', '▁used', '▁for', '▁', 'BPE', '▁bits', '.', '▁', 'I', 't', '▁can', '▁be', '▁up', '▁to', '▁', '128', '▁characters', '▁long', '.']
Uni Pieces: ['▁', 'T', 'hi', 's', '▁is', '▁a', '▁sample', '▁sentence', '▁used', '▁for', '▁', 'BPE', '▁bit', 's', '.', '▁', 'I', 't', '▁can', '▁be', '▁up', '▁to', '▁', '128', '▁characters', '▁long', '.']


In [34]:
def encode_and_pad(sp, texts):
    all_ids = []
    pad_id = sp.pad_id()  # should be 3 (trained with pad_id=3)

    for text in texts:
        ids = sp.encode(text, out_type=int)
        ids = ids[:TOKEN_LENGTH]

        while len(ids) < TOKEN_LENGTH:
            ids.append(pad_id)

        all_ids.append(ids)

    return np.array(all_ids, dtype=np.int32)


def encode_for_transformer(sp, texts):
    input_ids = encode_and_pad(sp, texts)

    # 1 for real tokens, 0 for pad tokens
    pad_id = sp.pad_id()
    attention_masks = (input_ids != pad_id).astype(np.int32)

    return input_ids, attention_masks

def encode_for_rnn(sp, texts):
    return encode_and_pad(sp, texts)

print("SentencePiece pad_id (bpe, uni):", sp_bpe.pad_id(), sp_uni.pad_id())
assert sp_bpe.pad_id() == PAD_ID and sp_uni.pad_id() == PAD_ID, f"Unexpected pad_id (expected {PAD_ID}). Got bpe={sp_bpe.pad_id()}, uni={sp_uni.pad_id()}"

SentencePiece pad_id (bpe, uni): 3 3


In [35]:
### BPE Generate data
Xb_train, att_b_mask_train = encode_for_transformer(sp_bpe, X_train_clean.tolist())
Xb_val, att_b_mask_val = encode_for_transformer(sp_bpe, X_val_clean.tolist())
Xb_test, att_b_mask_test = encode_for_transformer(sp_bpe, X_test_clean.tolist())

print(f"BPE train shape: {Xb_train.shape, att_b_mask_train.shape}")
print(f"BPE val shape: {Xb_val.shape, att_b_mask_val.shape}")
print(f"BPE test shape: {Xb_test.shape, att_b_mask_test.shape}")


BPE train shape: ((333447, 128), (333447, 128))
BPE val shape: ((41681, 128), (41681, 128))
BPE test shape: ((41681, 128), (41681, 128))


In [36]:
### UNI Generate Data
Xu_train = encode_for_rnn(sp_uni, X_train_clean.tolist())
Xu_val = encode_for_rnn(sp_uni, X_val_clean.tolist())
Xu_test = encode_for_rnn(sp_uni, X_test_clean.tolist())

print("UNI RNN train:", Xu_train.shape)
print("UNI RNN val:", Xu_val.shape)
print("UNI RNN test:", Xu_test.shape)

def make_rnn_dataset(X_ids, y_vals, seed=42):
    ds = tf.data.Dataset.from_tensor_slices((X_ids, y_vals))
    ds = ds.shuffle(SHUFFLE_BUFFER, seed=seed, reshuffle_each_iteration=True)
    ds = ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
    return ds

uni_rnn_train = make_rnn_dataset(Xu_train, y_train.values, seed=42)
uni_rnn_val   = tf.data.Dataset.from_tensor_slices((Xu_val, y_val.values)).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
uni_rnn_test  = tf.data.Dataset.from_tensor_slices((Xu_test, y_test.values)).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

UNI RNN train: (333447, 128)
UNI RNN val: (41681, 128)
UNI RNN test: (41681, 128)


In [37]:
### BPE TensorFlow input 
batch_size = BATCH_SIZE

def make_dataset(X_ids, X_mask, y, seed=42):
  data = tf.data.Dataset.from_tensor_slices(((X_ids, X_mask), y))
  data = data.shuffle(SHUFFLE_BUFFER, seed=seed, reshuffle_each_iteration=True)
  data = data.batch(batch_size).prefetch(tf.data.AUTOTUNE) 
  return data

bpe_train_data = make_dataset(Xb_train, att_b_mask_train, y_train.values, seed=42)

# tf.data.AUTOTUNE allows TensorFlow to automatically determine the optimal number of parallel calls for data loading and preprocessing
bpe_val_data = tf.data.Dataset.from_tensor_slices(((Xb_val, att_b_mask_val), y_val.values)).batch(batch_size).prefetch(tf.data.AUTOTUNE) 
bpe_test_data = tf.data.Dataset.from_tensor_slices(((Xb_test, att_b_mask_test), y_test.values)).batch(batch_size).prefetch(tf.data.AUTOTUNE)

In [38]:
### BPE - Balance classes
classes = np.sort(y_train.unique())
weights = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)

class_weights = {int(k): float(v) for k, v in zip(classes, weights)}
print(f"Class weights: {class_weights}")


Class weights: {0: 0.5732343809631868, 1: 0.4924503557725537, 2: 2.010436638570343, 3: 1.2119880490251669, 4: 1.455973277443018, 5: 4.639714476540324}


In [39]:
def build_bigru_classifier(vocab_size, num_classes, max_len=128, embed_dim=128, rnn_units=128, dropout=0.2):
    input_ids = tf.keras.Input(shape=(max_len,), dtype=tf.int32, name="input_ids")

    X = tf.keras.layers.Embedding(vocab_size, embed_dim, mask_zero=False, name="token_embedding")(input_ids)
    X = tf.keras.layers.Masking(mask_value=PAD_ID, name="pad_mask")(X)
    X = tf.keras.layers.Bidirectional(
        tf.keras.layers.GRU(rnn_units, return_sequences=False),
        name="bigru"
    )(X)

    X = tf.keras.layers.Dropout(dropout)(X)
    X = tf.keras.layers.Dense(DENSE_UNITS, activation="relu")(X)
    X = tf.keras.layers.Dropout(dropout)(X)

    output = tf.keras.layers.Dense(num_classes, activation="softmax", dtype="float32")(X)
    model = tf.keras.Model(inputs=input_ids, outputs=output, name="unigram_bigru")

    return model

In [40]:
### Train BiGru (Bidirectional Gated Recurrent Unit)
set_all_seeds(42)

num_classes = y.nunique()
uni_vocab_size = sp_uni.get_piece_size()

bigru_model = build_bigru_classifier(
    vocab_size=uni_vocab_size,
    num_classes=num_classes,
    max_len=TOKEN_LENGTH,
    embed_dim=EMBED_DIM,
    rnn_units=RNN_UNITS,
    dropout=RNN_DROPOUT
)

# sparse categorical needs one hot encoded lables
bigru_model.compile(
    optimizer=tf.keras.optimizers.AdamW(learning_rate=LEARNING_RATE, weight_decay=WEIGHT_DECAY),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=["accuracy"]
)

callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=PATIENCE,
        restore_best_weights=True
    )
]

history_rnn = bigru_model.fit(
    uni_rnn_train,
    validation_data=uni_rnn_val,
    epochs=EPOCHS,
    class_weight=class_weights,
    callbacks=callbacks
)

bigru_model.save("biGru_model.keras")

Epoch 1/7
2606/2606 ━━━━━━━━━━━━━━━━━━━━ 84s 32ms/step - accuracy: 0.7392 - loss: 0.5944 - val_accuracy: 0.9071 - val_loss: 0.2410
Epoch 2/7
2606/2606 ━━━━━━━━━━━━━━━━━━━━ 83s 32ms/step - accuracy: 0.9152 - loss: 0.1856 - val_accuracy: 0.9239 - val_loss: 0.1711
Epoch 3/7
2606/2606 ━━━━━━━━━━━━━━━━━━━━ 80s 31ms/step - accuracy: 0.9279 - loss: 0.1442 - val_accuracy: 0.9301 - val_loss: 0.1490
Epoch 4/7
2606/2606 ━━━━━━━━━━━━━━━━━━━━ 81s 31ms/step - accuracy: 0.9337 - loss: 0.1268 - val_accuracy: 0.9333 - val_loss: 0.1453
Epoch 5/7
2606/2606 ━━━━━━━━━━━━━━━━━━━━ 100s 38ms/step - accuracy: 0.9368 - loss: 0.1170 - val_accuracy: 0.9346 - val_loss: 0.1377
Epoch 6/7
2606/2606 ━━━━━━━━━━━━━━━━━━━━ 82s 31ms/step - accuracy: 0.9391 - loss: 0.1104 - val_accuracy: 0.9349 - val_loss: 0.1370
Epoch 7/7
2606/2606 ━━━━━━━━━━━━━━━━━━━━ 81s 31ms/step - accuracy: 0.9407 - loss: 0.1061 - val_accuracy: 0.9370 - val_loss: 0.1248


In [41]:
### BPE Model Definition
def build_transformer_classifier(vocab_size, num_classes, num_layers=2, max_len=128, num_heads=4, feed_forward_dim=256, rate=0.1, dense_units=128):
    input_ids = tf.keras.Input(shape=(max_len,), dtype=tf.int32, name="input_ids")
    input_mask = tf.keras.Input(shape=(max_len,), dtype=tf.int32, name="attention_mask")
    
    embedding_layer = TokenAndPositionEmbedding(max_len, vocab_size, embed_dim=EMBED_DIM)
    
    X = embedding_layer(input_ids)
    for _ in range(num_layers):
        X = TransformerBlock(embed_dim=EMBED_DIM, num_heads=num_heads, feed_forward_dim=feed_forward_dim, rate=rate)(X, tensor_mask=input_mask)

    X = tf.keras.layers.GlobalAveragePooling1D()(X)
    X = tf.keras.layers.Dropout(rate)(X)
    X = tf.keras.layers.Dense(dense_units, activation='relu')(X)
    X = tf.keras.layers.Dropout(rate)(X)
    
    output = tf.keras.layers.Dense(num_classes, activation='softmax', dtype='float32')(X)
    
    model = tf.keras.Model(inputs=[input_ids, input_mask], outputs=output)
    return model


In [42]:
### BPE Tokenizer and Vocab size
num_classes = y.nunique()
bpe_vocab_size = sp_bpe.get_piece_size()

print(f"BPE Vocab size: {bpe_vocab_size}")
print(f"Number of classes: {num_classes}")

BPE Vocab size: 8000
Number of classes: 6


In [43]:
y_pred_probs = bigru_model.predict(uni_rnn_test)
y_pred = np.argmax(y_pred_probs, axis=1)

print(classification_report(y_test, y_pred, digits=4))
print(confusion_matrix(y_test, y_pred))

326/326 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step
              precision    recall  f1-score   support

           0     0.9929    0.9513    0.9717     12119
           1     0.9947    0.9103    0.9506     14107
           2     0.7640    0.9910    0.8628      3456
           3     0.9164    0.9623    0.9388      5731
           4     0.9112    0.8755    0.8930      4771
           5     0.7176    0.9947    0.8337      1497

    accuracy                         0.9351     41681
   macro avg     0.8828    0.9475    0.9084     41681
weighted avg     0.9448    0.9351    0.9370     41681

[[11529    19     6   316   235    14]
 [   12 12841  1049    41    16   148]
 [    1    24  3425     4     2     0]
 [   47    17     2  5515   149     1]
 [   21     8     0   142  4177   423]
 [    1     1     1     0     5  1489]]


In [44]:
def evaluate_macro_f1(model, val_data):
    y_true = []
    y_pred = []

    for (batch_x, batch_y) in val_data:
        probs = model.predict(batch_x, verbose=0)
        preds = np.argmax(probs, axis=1)

        y_true.extend(batch_y.numpy().tolist())
        y_pred.extend(preds)

    return f1_score(y_true, y_pred, average="macro")

def train_one_config(vocab_size, num_classes, train_data, val_data, class_weights, token_length, num_layers, num_heads, ff_dim, dropout, lr, dense_units, run_log_dir):
    os.makedirs(run_log_dir, exist_ok=True)

    model = build_transformer_classifier(
        vocab_size=vocab_size,
        num_classes=num_classes,
        max_len=token_length,
        num_layers=num_layers,
        num_heads=num_heads,
        feed_forward_dim=ff_dim,
        rate=dropout,
        dense_units=dense_units
    )

    model.compile(
        optimizer=tf.keras.optimizers.AdamW(learning_rate=lr, weight_decay=WEIGHT_DECAY), 
        loss=tf.keras.losses.SparseCategoricalCrossentropy(),
        metrics=["accuracy"])
    
    early_stop_callback = tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=PATIENCE, restore_best_weights=True)
    tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=run_log_dir, histogram_freq=1, write_graph=True, update_freq="epoch")
    best_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(filepath=f"{run_log_dir}/best.keras", monitor="val_loss", save_best_only=True)
    latest_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(filepath=f"{run_log_dir}/latest.keras", save_best_only=False, save_freq="epoch")
    csv_callback = tf.keras.callbacks.CSVLogger(filename=f"{run_log_dir}/history.csv", append=True)

    history = model.fit(
        train_data,
        validation_data=val_data,
        epochs=EPOCHS,
        class_weight=class_weights,
        callbacks=[early_stop_callback, tensorboard_callback, latest_checkpoint_callback, best_checkpoint_callback, csv_callback],
        verbose=0
    )

    macro_f1 = evaluate_macro_f1(model, val_data)

    return model, history, macro_f1

In [ ]:
RESULTS_PATH = f"{log_dir}/results_so_far.csv"
DONE_PATH = f"{log_dir}/done_runs.jsonl"

os.makedirs(log_dir, exist_ok=True)

done = set()
if os.path.exists(DONE_PATH):
    with open(DONE_PATH, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                row = json.loads(line)
                done.add(row["run_log_dir"])

results = []

keys = list(sweep.keys())
for values in itertools.product(*[sweep[k] for k in keys]):
    config = dict(zip(keys, values))

    f1s = []
    f1s_used = []

    for seed in SEEDS:
        run_log_dir = f"{log_dir}/layers{config['num_layers']}_heads{config['num_heads']}_ff{config['ff_dim']}_drop{config['dropout']}_lr{config['lr']}_dense{config['dense_units']}_seed{seed}"

        if run_log_dir in done and os.path.exists(f"{run_log_dir}/best.keras"):
            continue
        
        set_all_seeds(seed)

        model, history, macro_f1 = train_one_config(
            vocab_size=VOCAB_SIZE,
            num_classes=num_classes,
            train_data=make_dataset(Xb_train, att_b_mask_train, y_train.values, seed=seed),
            val_data=bpe_val_data,
            class_weights=class_weights,
            token_length=TOKEN_LENGTH,
            num_layers=config["num_layers"],
            num_heads=config["num_heads"],
            ff_dim=config["ff_dim"],
            dropout=config["dropout"],
            lr=config["lr"],
            dense_units=config["dense_units"],
            run_log_dir=run_log_dir
        )

        f1s.append(macro_f1)
        f1s_used.append(seed)

        with open(DONE_PATH, "a", encoding="utf-8") as f:
            f.write(json.dumps({"run_log_dir": run_log_dir}) + "\n")
            done.add(run_log_dir)

    if len(f1s) == 0:
        continue

    row = {
        **config,
        "macro_f1_mean": float(np.mean(f1s)),
        "macro_f1_std": float(np.std(f1s)),
        "seeds_ran": ", ".join(map(str, f1s_used))
    }

    results.append(row)

    results_df_partial = pd.DataFrame([row])
    header = not os.path.exists(RESULTS_PATH)
    results_df_partial.to_csv(RESULTS_PATH, mode="a", header=header, index=False)

print("Finished sweep. Selecting best config...")

if os.path.exists(RESULTS_PATH):
    results_df = pd.read_csv(RESULTS_PATH)
    results_df = results_df.sort_values(by=["macro_f1_mean", "macro_f1_std"], ascending=[False, True])
else:
    results_df = pd.DataFrame(results).sort_values(by=["macro_f1_mean", "macro_f1_std"], ascending=[False, True])

results_df.head(10)

2026-03-04 09:03:32.405482: I external/local_xla/xla/service/service.cc:163] XLA service 0x7f14087bceb0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2026-03-04 09:03:32.405595: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (0): NVIDIA GeForce RTX 3070 Laptop GPU, Compute Capability 8.6
2026-03-04 09:03:32.525024: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2026-03-04 09:03:33.606101: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2026-03-04 09:03:33.606177: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because

In [ ]:
### BPE Train 🥳🥳🥳
# bpe_model = build_transformer_classifier(vocab_size=bpe_vocab_size, num_classes=num_classes, max_len=TOKEN_LENGTH)
# bpe_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=3e-4), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# callbacks = [tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)]
# history = bpe_model.fit(bpe_train_data, validation_data=bpe_val_data, epochs=5, class_weight=class_weights, callbacks=callbacks)

# commented out to test params table

best = results_df.iloc[0].to_dict()
print(best)

seed = 42
set_all_seeds(seed)

train_data_seeded = make_dataset(Xb_train, att_b_mask_train, y_train.values, seed=seed)

bpe_model, history, _ = train_one_config(
    vocab_size=bpe_vocab_size,
    num_classes=num_classes,
    train_data=train_data_seeded,
    val_data=bpe_val_data,
    class_weights=class_weights,
    token_length=TOKEN_LENGTH,
    num_layers=int(best["num_layers"]),
    num_heads=int(best["num_heads"]),
    ff_dim=int(best["ff_dim"]),
    dropout=float(best["dropout"]),
    lr=float(best["lr"]),
    dense_units=int(best["dense_units"]),
    run_log_dir=f"{log_dir}/best_run_seed{seed}")

print("Saving model")
bpe_model.save("emotion_transformer.keras")

In [ ]:
# Predict
y_pred_probs = bpe_model.predict(bpe_test_data)
y_pred = np.argmax(y_pred_probs, axis=1)

print(classification_report(y_test, y_pred, digits=4))
print(confusion_matrix(y_test, y_pred))


In [ ]:
tf.keras.utils.plot_model(bpe_model, to_file='bpe_model.png', show_shapes=True, show_layer_names=True)

print(history.history.keys())

plt.figure()
plt.plot(history.history["loss"], label="train_loss")
plt.plot(history.history["val_loss"], label="val_loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.title("Training vs Validation Loss")
plt.show()

if "accuracy" in history.history:
    plt.figure()
    plt.plot(history.history["accuracy"], label="train_acc")
    plt.plot(history.history["val_accuracy"], label="val_acc")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.title("Training vs Validation Accuracy")
    plt.show()

In [ ]:
plt.figure()
plt.plot(history_rnn.history["loss"], label="train_loss")
plt.plot(history_rnn.history["val_loss"], label="val_loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.title("BiGRU: Training vs Validation Loss")
plt.show()
    
if "accuracy" in history_rnn.history:
    plt.figure()
    plt.plot(history_rnn.history["accuracy"], label="train_acc")
    plt.plot(history_rnn.history["val_accuracy"], label="val_acc")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.title("BiGRU: Training vs Validation Accuracy")
    plt.show()

In [ ]:
### Test on new sentences

def encode_one(sentence_piece, text: str, max_len: int, pad_id: int = PAD_ID):
    ids = sentence_piece.encode(text.strip(), out_type=int)    
    ids = ids[:max_len]
    mask = [1] * len(ids)
    while len(ids) < max_len:
            ids.append(pad_id)
            mask.append(0)    
    return np.array([ids], dtype=np.int32), np.array([mask], dtype=np.int32)
    
text_samples = [
    "I have work tomorrow and I am not looking forward to it.",
    "I feel happy",
    "I have work tomorrow and I am looking forward to it.",
    "I have work tomorrow and I am not looking forward to it, but I love my job.",
    "I love my job and I am looking forward to work tomorrow."   
]

for text in text_samples:
    ids, m = encode_one(sp_bpe, text, TOKEN_LENGTH)
    probs = bpe_model.predict((ids, m), verbose=0)[0]
    pred = int(np.argmax(probs))
    print(f"Text: {text}\nPredicted Emotion: {emotion_map[pred]}")
    
    top3 = np.argsort(probs)[-3:][::-1]
    
    print(f"Top 3 Predictions:")
    for top in top3:
        print(f"{emotion_map[top]}: {probs[top]:.2f}")
        
    print()

In [ ]:
def encode_one_rnn(sentence_piece, text: str, max_len: int):
    ids = sentence_piece.encode(text.strip(), out_type=int)
    ids = ids[:max_len]
    while len(ids) < max_len:
        ids.append(PAD_ID)

    X = np.array([ids], dtype=np.int32)
    X[X == PAD_ID] = 0
    return X

for text in text_samples:
    X_one = encode_one_rnn(sp_uni, text, TOKEN_LENGTH)
    probs = bigru_model.predict(X_one, verbose=0)[0]
    pred = int(np.argmax(probs))

    print(f"Text: {text}")
    print(f"Predicted Emotion: {emotion_map[pred]}")
    top3 = np.argsort(probs)[-3:][::-1]
    print("Top 3:")
    for idx in top3:
        print(f"  {emotion_map[idx]}: {probs[idx]:.2f}")
    print()